tls:
  stores:
    default:
      certificates:
        - certFile: /etc/ssl/new-certs/cogni-test.ru_cert.pem
          keyFile: /etc/ssl/new-certs/cogni-test.ru_private_key.pem
          stores:
            - default
        - certFile: /etc/ssl/new-certs/cogni-rhythm.ru_cert.pem
          keyFile: /etc/ssl/new-certs/cogni-rhythm.ru_private_key.pem
          stores:
            - default

http:
  routers:
    dev-redirect:
      rule: "Host(`dev.cogni-test.ru`)"
      entrypoints:
        - websecure
      tls: {}
      middlewares:
        - dev-redirect
      service: noop@file
  middlewares:
    dev-redirect:
      redirectRegex:
        regex: "^https://dev\\.cogni-test\\.ru/(.*)"
        replacement: "https://cogni-test.ru/${1}"
        permanent: true
  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:80"
